//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table
{
    
    // KEY:EnemyName
    // 
    public partial class TestTable
    {
        private string _EnemyName;
        private int _EnemyID;
        private int _EnemyHealth;
        private int _EnemyAttack;
        private int _UnlockLevel;
        private int _Weight;
        // intCode
        public string EnemyName
        {
            get
            {
                return this._EnemyName;
            }
            set
            {
                this._EnemyName = value;
            }
        }
        // 
        public int EnemyID
        {
            get
            {
                return this._EnemyID;
            }
            set
            {
                this._EnemyID = value;
            }
        }
        // 
        public int EnemyHealth
        {
            get
            {
                return this._EnemyHealth;
            }
            set
            {
                this._EnemyHealth = value;
            }
        }
        // 
        public int EnemyAttack
        {
            get
            {
                return this._EnemyAttack;
            }
            set
            {
                this._EnemyAttack = value;
            }
        }
        // 
        public int UnlockLevel
        {
            get
            {
                return this._UnlockLevel;
            }
            set
            {
                this._UnlockLevel = value;
            }
        }
        // 
        public int Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this._Weight = value;
            }
        }
    }
}
